export interface Review {
  id: number;
  name: string;
  date: string; // ISO date string or formatted date
  rating: number; // 1-5 stars
  text: string;
  photo?: string; // optional customer photo/avatar
}

export const reviews: Review[] = [
  {
    "id": 1,
    "name": "Andres Felipe",
    "date": "2025-12-27",
    "rating": 5,
    "text": "I rented a Tesla Model Y for a few days during my vacation in Miami, and the experience was outstanding from start to finish. The car was in perfect condition, and its advanced driving technology truly makes a difference — after this experience, Tesla is definitely my top choice.\n\nThe service was equally exceptional: the vehicle was delivered and picked up directly at my hotel, always on time and with great professionalism. Everything was seamless, smooth, and stress-free.\n\nA truly first-class experience. Highly recommended.",
    "photo": "/reviews/AndresFelipe2025-12-27.jpg"
  },
  {
    "id": 2,
    "name": "Raynald",
    "date": "2025-12-27",
    "rating": 5,
    "text": "Excellent communication, easy access, clean inside and out . Will rent again !",
    },
  {
    "id": 8,
    "name": "Andrew",
    "date": "2025-12-23",
    "rating": 5,
    "text": "Excellent car and excellent host. Very responsive and I loved that the self driving Tesla was super clean and drove great.",
    },
  {
    "id": 10,
    "name": "Arnoldas",
    "date": "2025-12-22",
    "rating": 5,
    "text": "amazing car and amazing host!\n\nTotally worth the cost!",
    "photo": "/reviews/Arnoldas2025-12-22.jpg"
  },
  {
    "id": 11,
    "name": "Jacob",
    "date": "2025-12-22",
    "rating": 5,
    "text": "Easy to work with and the car was in great condition.",
    },
  {
    "id": 12,
    "name": "Paul",
    "date": "2025-12-22",
    "rating": 5,
    "text": "This is an awesome awesome host very accommodating very kind and has wonderful. Vehicles will definitely rent again.",
    "photo": "/reviews/Paul2025-12-22.jpg"
  },
  {
    "id": 14,
    "name": "Christian",
    "date": "2025-12-21",
    "rating": 5,
    "text": "",
    "photo": "/reviews/Christian2025-12-21.jpg"
  },
  {
    "id": 15,
    "name": "Nickolas",
    "date": "2025-12-21",
    "rating": 5,
    "text": "They were so amazing to work with! The car was spotless and they even delivered it to my hotel! Definitely recommend!!!!",
    },
  {
    "id": 16,
    "name": "Steven",
    "date": "2025-12-21",
    "rating": 5,
    "text": "She was an awesome host, very helpful and timely.",
    },
  {
    "id": 17,
    "name": "Lee",
    "date": "2025-12-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 18,
    "name": "Evgeny",
    "date": "2025-12-19",
    "rating": 5,
    "text": "Great rental experience. The car was very clean, the host was extremely polite and helpful, and the customer support was excellent. Highly recommend this service!",
    },
  {
    "id": 19,
    "name": "Vahé",
    "date": "2025-12-16",
    "rating": 5,
    "text": "Great car and service.",
    },
  {
    "id": 20,
    "name": "Christopher",
    "date": "2025-12-15",
    "rating": 5,
    "text": "The best place in America to rent a car hands down they go they go above and beyond to help you out nothing is too much trouble",
    },
  {
    "id": 21,
    "name": "Maurice",
    "date": "2025-12-14",
    "rating": 5,
    "text": "You guys are the best in all of Miami",
    },
  {
    "id": 22,
    "name": "John",
    "date": "2025-12-14",
    "rating": 5,
    "text": "",
    },
  {
    "id": 23,
    "name": "Jonathan",
    "date": "2025-12-13",
    "rating": 5,
    "text": "",
    },
  {
    "id": 24,
    "name": "Evgeniy",
    "date": "2025-12-13",
    "rating": 5,
    "text": "",
    },
  {
    "id": 25,
    "name": "Zachary",
    "date": "2025-12-13",
    "rating": 5,
    "text": "",
    },
  {
    "id": 26,
    "name": "Druskeily",
    "date": "2025-12-12",
    "rating": 5,
    "text": "Great car. Great host! She helped us a lot! Definitely will get a car with her again",
    },
  {
    "id": 27,
    "name": "Leonardo",
    "date": "2025-12-12",
    "rating": 5,
    "text": "",
    },
  {
    "id": 28,
    "name": "Kevin",
    "date": "2025-12-11",
    "rating": 5,
    "text": "",
    },
  {
    "id": 29,
    "name": "Brian",
    "date": "2025-12-10",
    "rating": 5,
    "text": "",
    },
  {
    "id": 30,
    "name": "Thomas",
    "date": "2025-12-09",
    "rating": 5,
    "text": "Service was amazing! Grate people 🙏🏻📈",
    },
  {
    "id": 31,
    "name": "Juan",
    "date": "2025-12-08",
    "rating": 5,
    "text": "Fantastic. As usual",
    },
  {
    "id": 32,
    "name": "Leonel",
    "date": "2025-12-08",
    "rating": 5,
    "text": "Great car and host",
    },
  {
    "id": 33,
    "name": "Baylee",
    "date": "2025-12-07",
    "rating": 5,
    "text": "",
    },
  {
    "id": 34,
    "name": "Piotr",
    "date": "2025-12-07",
    "rating": 5,
    "text": "Great",
    },
  {
    "id": 35,
    "name": "Gregory",
    "date": "2025-12-07",
    "rating": 4,
    "text": "Great trip. the key did not work but the app worked. Owner did a good job communicating back.",
    },
  {
    "id": 36,
    "name": "Arsenio",
    "date": "2025-12-06",
    "rating": 5,
    "text": "",
    },
  {
    "id": 37,
    "name": "Daniel",
    "date": "2025-12-06",
    "rating": 5,
    "text": "Great car, great host",
    },
  {
    "id": 38,
    "name": "Devy",
    "date": "2025-12-06",
    "rating": 5,
    "text": "La prise en main était simple, les aides de l’hôte parfait , le temps de réponse parfait , et le véhicule en parfait état . Je recommande à n’importe qui de prendre ce véhicule pour un trip en floride .\n\nLa prochaine fois que je reviens je reprends des véhicules avec eux c’est sur !!",
    },
  {
    "id": 39,
    "name": "Jacob",
    "date": "2025-12-05",
    "rating": 5,
    "text": "Quality, communication everything was perfect",
    },
  {
    "id": 40,
    "name": "sachin",
    "date": "2025-12-04",
    "rating": 5,
    "text": "",
    },
  {
    "id": 41,
    "name": "Miguel",
    "date": "2025-12-03",
    "rating": 5,
    "text": "Always great service and clean vehicles",
    },
  {
    "id": 42,
    "name": "Marc",
    "date": "2025-12-02",
    "rating": 5,
    "text": "Absolutely the best to work with. Highly recommend! Easy to work with, Yainery and her family have a great line up of cars, extremely responsive, and just overall excellent to work with. No brainer if you are looking for a Tesla to get around the area.",
    },
  {
    "id": 43,
    "name": "justin",
    "date": "2025-12-02",
    "rating": 5,
    "text": "",
    },
  {
    "id": 44,
    "name": "Katelin",
    "date": "2025-12-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 45,
    "name": "FELIPE",
    "date": "2025-11-30",
    "rating": 5,
    "text": "Top!!! Great!!! Thank for all",
    },
  {
    "id": 46,
    "name": "Vincent",
    "date": "2025-11-30",
    "rating": 5,
    "text": "",
    },
  {
    "id": 47,
    "name": "Matthew",
    "date": "2025-11-30",
    "rating": 5,
    "text": "THANK YOU SO MUCH",
    },
  {
    "id": 48,
    "name": "SHANETRIA",
    "date": "2025-11-30",
    "rating": 5,
    "text": "",
    },
  {
    "id": 49,
    "name": "Rachel",
    "date": "2025-11-29",
    "rating": 5,
    "text": "We rent from Yainery everytime we’re in Miami and it’s always perfect! Thank you so much!",
    },
  {
    "id": 50,
    "name": "Benjamin",
    "date": "2025-11-29",
    "rating": 5,
    "text": "The Model Y was great. Such a wonderful car to drive dash and to let it drive you in insane Miami traffic. Super safe. The host is wonderful and super accommodating. Overall a great experience.",
    },
  {
    "id": 51,
    "name": "Ana",
    "date": "2025-11-29",
    "rating": 5,
    "text": "Great car. Love self driving",
    },
  {
    "id": 52,
    "name": "Javis",
    "date": "2025-11-28",
    "rating": 5,
    "text": "",
    },
  {
    "id": 53,
    "name": "Patrick",
    "date": "2025-11-28",
    "rating": 4,
    "text": "Inside a car windshield is very dirty",
    },
  {
    "id": 54,
    "name": "Jorge",
    "date": "2025-11-27",
    "rating": 5,
    "text": "Excelente servicio. Excelente carro.\nMuy atentos, siempre disponibles.\nRecomendado al 100%\nGracias !!",
    },
  {
    "id": 55,
    "name": "Dingsheng",
    "date": "2025-11-27",
    "rating": 5,
    "text": "",
    },
  {
    "id": 56,
    "name": "Marcelo",
    "date": "2025-11-26",
    "rating": 5,
    "text": "Renting from Yainery was an outstanding experience from start to finish. The Tesla was in perfect condition, clean, smooth, fully charged, and a pleasure to drive. Everything worked flawlessly, and the car felt brand-new.\n\nCommunication with Yainery was exceptional. She was always friendly, fast to respond, and genuinely committed to making the trip as easy and comfortable as possible. Pickup and drop-off were seamless, and her flexibility made a big difference in my travel schedule.\n\nI highly recommend renting from her. Great host, great car, and an overall top-notch experience. I would definitely book with Yainery again!",
    },
  {
    "id": 57,
    "name": "Jimmie",
    "date": "2025-11-25",
    "rating": 5,
    "text": "Great car, great host",
    },
  {
    "id": 58,
    "name": "Jorge",
    "date": "2025-11-25",
    "rating": 5,
    "text": "",
    },
  {
    "id": 59,
    "name": "Jonathan",
    "date": "2025-11-24",
    "rating": 5,
    "text": "",
    },
  {
    "id": 60,
    "name": "Zeandre",
    "date": "2025-11-24",
    "rating": 5,
    "text": "Amazing car. Amazing Host. Easy Pick up at your convenience.",
    },
  {
    "id": 61,
    "name": "Alejandro",
    "date": "2025-11-24",
    "rating": 5,
    "text": "",
    },
  {
    "id": 62,
    "name": "Andres",
    "date": "2025-11-22",
    "rating": 5,
    "text": "",
    },
  {
    "id": 63,
    "name": "Lucia",
    "date": "2025-11-22",
    "rating": 5,
    "text": "",
    },
  {
    "id": 64,
    "name": "Jeremiah",
    "date": "2025-11-21",
    "rating": 5,
    "text": "",
    },
  {
    "id": 65,
    "name": "Marcelo",
    "date": "2025-11-21",
    "rating": 5,
    "text": "",
    },
  {
    "id": 66,
    "name": "Rachelle",
    "date": "2025-11-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 67,
    "name": "Breno",
    "date": "2025-11-19",
    "rating": 5,
    "text": "",
    },
  {
    "id": 68,
    "name": "joel",
    "date": "2025-11-19",
    "rating": 5,
    "text": "",
    },
  {
    "id": 69,
    "name": "JUAN",
    "date": "2025-11-18",
    "rating": 5,
    "text": "",
    },
  {
    "id": 70,
    "name": "Carsten",
    "date": "2025-11-17",
    "rating": 5,
    "text": "Great car and great service. Absolutely loved the Fuil Self Driving Experience!",
    },
  {
    "id": 71,
    "name": "Nayla",
    "date": "2025-11-17",
    "rating": 5,
    "text": "Excellent Host!\n\nI had a great experience renting from her. The car was super clean, reliable, and exactly as described. Communication was fast and friendly from the beginning to the end of the trip. She made the whole process easy and stress-free. I would definitely rent from her again and highly recommend her to anyone using Turo. Thank you for the amazing service!",
    },
  {
    "id": 72,
    "name": "Maurice",
    "date": "2025-11-16",
    "rating": 5,
    "text": "",
    },
  {
    "id": 73,
    "name": "Demarkis",
    "date": "2025-11-16",
    "rating": 5,
    "text": "",
    },
  {
    "id": 74,
    "name": "Mario",
    "date": "2025-11-16",
    "rating": 5,
    "text": "",
    },
  {
    "id": 75,
    "name": "Josh",
    "date": "2025-11-16",
    "rating": 5,
    "text": "",
    },
  {
    "id": 76,
    "name": "Elliott",
    "date": "2025-11-16",
    "rating": 5,
    "text": "She was very accommodating and easy to work with! Made my trip easier from pick up to drop off! Would definitely use her cars again.",
    },
  {
    "id": 77,
    "name": "Omar Razeq",
    "date": "2025-11-15",
    "rating": 5,
    "text": "",
    },
  {
    "id": 78,
    "name": "Heiko Kurt",
    "date": "2025-11-15",
    "rating": 5,
    "text": "Everything worked fluent and fine, the owner was always available and willing to support via chat and personally as soon as possible even at night time, always very kind communication. Experience with the car and FSD 13.2.9 was amazing (v14 already shipping soon), don't want to miss it ever again (but have to, since still not allowed in home country).",
    },
  {
    "id": 79,
    "name": "Corey",
    "date": "2025-11-15",
    "rating": 5,
    "text": "Car was amazing. Highly recommend. Used the FSD a ton. Thank you!",
    },
  {
    "id": 80,
    "name": "Balázs",
    "date": "2025-11-14",
    "rating": 5,
    "text": "Everything was perfect. FSD was awesome.",
    },
  {
    "id": 81,
    "name": "Marcelo",
    "date": "2025-11-13",
    "rating": 5,
    "text": "Incredible host!",
    },
  {
    "id": 82,
    "name": "Gianni",
    "date": "2025-11-13",
    "rating": 5,
    "text": "",
    },
  {
    "id": 83,
    "name": "Christopher",
    "date": "2025-11-13",
    "rating": 5,
    "text": "",
    },
  {
    "id": 84,
    "name": "Zain",
    "date": "2025-11-12",
    "rating": 5,
    "text": "Perfect. Great vehicle. Easy to drive. Love the self drive auto pilot feature!!",
    },
  {
    "id": 85,
    "name": "Sakshi",
    "date": "2025-11-12",
    "rating": 5,
    "text": "",
    },
  {
    "id": 86,
    "name": "Gabo",
    "date": "2025-11-12",
    "rating": 5,
    "text": "I wish there was a 6 star for this",
    },
  {
    "id": 87,
    "name": "Camilo",
    "date": "2025-11-12",
    "rating": 5,
    "text": "Thank you for the great service!",
    },
  {
    "id": 88,
    "name": "Bernd",
    "date": "2025-11-11",
    "rating": 5,
    "text": "The best car experience ever. Both the host, the car (cbtrk) and the software (fsd) were exceptional to us",
    },
  {
    "id": 89,
    "name": "Asha",
    "date": "2025-11-10",
    "rating": 5,
    "text": "everything was wonderful.. Pick up and drop off was easy .. The host was very professional.",
    },
  {
    "id": 90,
    "name": "Aidan",
    "date": "2025-11-10",
    "rating": 5,
    "text": "Beautiful ride!",
    },
  {
    "id": 91,
    "name": "Kevin",
    "date": "2025-11-10",
    "rating": 5,
    "text": "Excellent host!",
    },
  {
    "id": 92,
    "name": "Duarte",
    "date": "2025-11-09",
    "rating": 5,
    "text": "So responsive, easy and great service! Highly recommend!",
    },
  {
    "id": 93,
    "name": "Jalen",
    "date": "2025-11-09",
    "rating": 5,
    "text": "",
    },
  {
    "id": 94,
    "name": "Christopher",
    "date": "2025-11-09",
    "rating": 5,
    "text": "I would only rent from these people in South Florida They give such good service. This is my third car from them now. Friendly and efficient, and always with the very latest software, which is why I rent this car.",
    },
  {
    "id": 95,
    "name": "Zahkir",
    "date": "2025-11-09",
    "rating": 5,
    "text": "",
    },
  {
    "id": 96,
    "name": "Noah",
    "date": "2025-11-08",
    "rating": 5,
    "text": "",
    },
  {
    "id": 97,
    "name": "Saul",
    "date": "2025-11-06",
    "rating": 5,
    "text": "",
    },
  {
    "id": 98,
    "name": "Christopher",
    "date": "2025-11-05",
    "rating": 5,
    "text": "Absolutely fantastic and completely faultless great service",
    },
  {
    "id": 99,
    "name": "Michael",
    "date": "2025-11-05",
    "rating": 5,
    "text": "",
    },
  {
    "id": 100,
    "name": "CYRIL",
    "date": "2025-11-05",
    "rating": 5,
    "text": "Fantastic host ! I recommend !",
    },
  {
    "id": 101,
    "name": "Heidi",
    "date": "2025-11-04",
    "rating": 5,
    "text": "Absolutely fantastic, owner was so helpful as this was my first time driving a Tesla and I was definitely more than needy in requiring some support! She was lovely and responsive!",
    },
  {
    "id": 102,
    "name": "Brian",
    "date": "2025-11-03",
    "rating": 5,
    "text": "",
    },
  {
    "id": 103,
    "name": "Franco",
    "date": "2025-11-02",
    "rating": 5,
    "text": "",
    },
  {
    "id": 104,
    "name": "Roxanne",
    "date": "2025-11-02",
    "rating": 5,
    "text": "",
    },
  {
    "id": 105,
    "name": "Bradley",
    "date": "2025-11-01",
    "rating": 4,
    "text": "Car was great. Really good. Self driving is amazing. 🤩. Small issues were during pick up. A better description of location would have helped. After 12hr flight. 🥱 Statement upon renting that $25 parking fee not covered by the airport fee of $72 would be good. Cannot see where that was on the booking. But overall awesome.",
    },
  {
    "id": 106,
    "name": "Antonio",
    "date": "2025-11-01",
    "rating": 5,
    "text": "Yay is an incredible host, we such an amazing experience, everything when perfectly smooth. A dream come true! Thank you very much!",
    },
  {
    "id": 107,
    "name": "Alex",
    "date": "2025-10-31",
    "rating": 5,
    "text": "",
    },
  {
    "id": 108,
    "name": "Beat",
    "date": "2025-10-30",
    "rating": 5,
    "text": "Simple and friendly communication with the host. Clean and reliable car. Thank you, it was an amazing trip.",
    },
  {
    "id": 109,
    "name": "La’Toya",
    "date": "2025-10-30",
    "rating": 5,
    "text": "",
    },
  {
    "id": 110,
    "name": "Jose",
    "date": "2025-10-29",
    "rating": 5,
    "text": "Amazing host. Smooth process renting vehicle. Will definitely use again.",
    },
  {
    "id": 111,
    "name": "Pablo",
    "date": "2025-10-29",
    "rating": 5,
    "text": "Great car, Great host!",
    },
  {
    "id": 112,
    "name": "Alex",
    "date": "2025-10-27",
    "rating": 5,
    "text": "",
    },
  {
    "id": 113,
    "name": "Landon",
    "date": "2025-10-26",
    "rating": 5,
    "text": "Great ride, easy pick up and drop off",
    },
  {
    "id": 114,
    "name": "Robert",
    "date": "2025-10-26",
    "rating": 5,
    "text": "Host was very responsive and the car was very clean and ran great. Would highly recommended booking. Fun car!",
    },
  {
    "id": 115,
    "name": "Jamie",
    "date": "2025-10-26",
    "rating": 5,
    "text": "Everything was wonderful, highly recommend. The Tesla took some getting used to (would recommend googling how to use it first if you haven’t driven one before), but it was a true pleasure. Thank you! Highly recommend.",
    },
  {
    "id": 116,
    "name": "Andrea",
    "date": "2025-10-26",
    "rating": 5,
    "text": "",
    },
  {
    "id": 117,
    "name": "Kailan",
    "date": "2025-10-26",
    "rating": 5,
    "text": "",
    },
  {
    "id": 118,
    "name": "William",
    "date": "2025-10-26",
    "rating": 5,
    "text": "",
    },
  {
    "id": 119,
    "name": "Michael",
    "date": "2025-10-25",
    "rating": 5,
    "text": "Excellent host and very accommodating. Great car and great experience!",
    },
  {
    "id": 120,
    "name": "Silemy",
    "date": "2025-10-24",
    "rating": 5,
    "text": "",
    },
  {
    "id": 121,
    "name": "ANTOINE",
    "date": "2025-10-24",
    "rating": 5,
    "text": "",
    },
  {
    "id": 122,
    "name": "Dustin",
    "date": "2025-10-22",
    "rating": 5,
    "text": "",
    },
  {
    "id": 123,
    "name": "Jonvonie",
    "date": "2025-10-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 124,
    "name": "Moises",
    "date": "2025-10-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 125,
    "name": "Jesus",
    "date": "2025-10-19",
    "rating": 5,
    "text": "Amazing host, hope to rent with her again next time I visit Miami, very much recommended!",
    },
  {
    "id": 126,
    "name": "Adonis",
    "date": "2025-10-19",
    "rating": 5,
    "text": "A++",
    },
  {
    "id": 127,
    "name": "Roxanne",
    "date": "2025-10-18",
    "rating": 5,
    "text": "",
    },
  {
    "id": 128,
    "name": "Rudi",
    "date": "2025-10-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 129,
    "name": "Diana",
    "date": "2025-10-15",
    "rating": 5,
    "text": "We have a very nice experience renting the car and the host super kind and best service",
    },
  {
    "id": 130,
    "name": "Jose Daniel",
    "date": "2025-10-14",
    "rating": 5,
    "text": "Excellent service.",
    },
  {
    "id": 131,
    "name": "Krystal",
    "date": "2025-10-14",
    "rating": 5,
    "text": "",
    },
  {
    "id": 132,
    "name": "Teja",
    "date": "2025-10-14",
    "rating": 5,
    "text": "",
    },
  {
    "id": 133,
    "name": "Marcel",
    "date": "2025-10-14",
    "rating": 5,
    "text": "",
    },
  {
    "id": 134,
    "name": "Davide",
    "date": "2025-10-13",
    "rating": 5,
    "text": "All great!",
    },
  {
    "id": 135,
    "name": "Thalia",
    "date": "2025-10-13",
    "rating": 5,
    "text": "",
    },
  {
    "id": 136,
    "name": "Taehyun",
    "date": "2025-10-13",
    "rating": 5,
    "text": "",
    },
  {
    "id": 137,
    "name": "Marianna",
    "date": "2025-10-13",
    "rating": 5,
    "text": "Great car. Easy pick up and drop off. Host very responsive throughout the experience. Will rent again!",
    },
  {
    "id": 138,
    "name": "Daryl",
    "date": "2025-10-13",
    "rating": 5,
    "text": "Everything was fantastic! Thank you!",
    },
  {
    "id": 139,
    "name": "Turo",
    "date": "2025-10-13",
    "rating": 5,
    "text": "The host cancelled this trip last minute. This message was automatically posted by Turo.",
    },
  {
    "id": 140,
    "name": "Allison",
    "date": "2025-10-12",
    "rating": 5,
    "text": "Everything was great!",
    },
  {
    "id": 141,
    "name": "Andrew",
    "date": "2025-10-12",
    "rating": 5,
    "text": "",
    },
  {
    "id": 142,
    "name": "Matthew",
    "date": "2025-10-12",
    "rating": 5,
    "text": "Great. Everything was perfect and would definitely recommend and use host again.",
    },
  {
    "id": 143,
    "name": "Muhammad",
    "date": "2025-10-12",
    "rating": 5,
    "text": "Seamless rental! Yainery’s spotless 2025 Tesla Model 3 ran flawlessly. Easy pickup/drop-off and lightning-fast responses—even at midnight—made the trip stress-free. Can’t wait to rent again in Miami. 5 stars!",
    },
  {
    "id": 144,
    "name": "David",
    "date": "2025-10-11",
    "rating": 5,
    "text": "",
    },
  {
    "id": 145,
    "name": "david",
    "date": "2025-10-11",
    "rating": 5,
    "text": "Great host ! Everthing perfect !!!",
    },
  {
    "id": 146,
    "name": "joseph",
    "date": "2025-10-11",
    "rating": 5,
    "text": "",
    },
  {
    "id": 147,
    "name": "Cierra",
    "date": "2025-10-10",
    "rating": 5,
    "text": "Yainery was an exceptional host! It was my first Turo and Tesla experience and she was extremely responsive and promptly. The car is immaculate and I will certainly rent from her again. Thank you!",
    },
  {
    "id": 148,
    "name": "Fausto",
    "date": "2025-10-10",
    "rating": 5,
    "text": "A wonderful experience, the hosts were super friendly, always available to answer any questions or messages.",
    },
  {
    "id": 149,
    "name": "Juan Pablo",
    "date": "2025-10-08",
    "rating": 5,
    "text": "",
    },
  {
    "id": 150,
    "name": "Chloe",
    "date": "2025-10-07",
    "rating": 5,
    "text": "",
    },
  {
    "id": 151,
    "name": "Ivan",
    "date": "2025-10-07",
    "rating": 5,
    "text": "",
    },
  {
    "id": 152,
    "name": "Tkerria",
    "date": "2025-10-07",
    "rating": 5,
    "text": "Everything Was Amazing",
    },
  {
    "id": 153,
    "name": "Jennifer",
    "date": "2025-10-07",
    "rating": 5,
    "text": "",
    },
  {
    "id": 154,
    "name": "E",
    "date": "2025-10-07",
    "rating": 5,
    "text": "",
    },
  {
    "id": 155,
    "name": "Jessica",
    "date": "2025-10-07",
    "rating": 5,
    "text": "Very great host. Car was clean and well kept. Didn’t have any problems. Host was very responsive when I asked questions. Thank you!",
    },
  {
    "id": 156,
    "name": "Justin",
    "date": "2025-10-06",
    "rating": 5,
    "text": "The car was clean, easy to find and unlock remotely, overall an enjoyable experience and perfect choice for the weekend.\nThanks again!",
    },
  {
    "id": 157,
    "name": "Katarina",
    "date": "2025-10-06",
    "rating": 5,
    "text": "",
    },
  {
    "id": 158,
    "name": "Josh",
    "date": "2025-10-06",
    "rating": 5,
    "text": "Great car! Wonderful host",
    },
  {
    "id": 159,
    "name": "John",
    "date": "2025-10-06",
    "rating": 5,
    "text": "The car was great and all instructions were thorough, if in Miami again, we will be renting from you again!!",
    },
  {
    "id": 160,
    "name": "vegard",
    "date": "2025-10-05",
    "rating": 5,
    "text": "Host and car has been amazing! Always a pleasure renting",
    },
  {
    "id": 161,
    "name": "Christopher",
    "date": "2025-10-05",
    "rating": 5,
    "text": "The car was in amazing condition. It drove great. Very clean inside and out. Yainery was very friendly and accommodating. Our entire rental experience was nothing short of perfect. Thank you!! 🙏😊",
    },
  {
    "id": 162,
    "name": "Nikki",
    "date": "2025-10-04",
    "rating": 5,
    "text": "Excellent vehicle! Spectacular host. Smooth and flawless experience. Wonderful trip. Definitely recommend and will rent from them again! ⭐️",
    },
  {
    "id": 163,
    "name": "Minhthu",
    "date": "2025-10-03",
    "rating": 5,
    "text": "",
    },
  {
    "id": 164,
    "name": "Breno",
    "date": "2025-10-02",
    "rating": 5,
    "text": "",
    },
  {
    "id": 165,
    "name": "Hugo",
    "date": "2025-10-02",
    "rating": 5,
    "text": "",
    },
  {
    "id": 166,
    "name": "Sandro",
    "date": "2025-10-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 167,
    "name": "Ivan",
    "date": "2025-10-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 168,
    "name": "Leo",
    "date": "2025-10-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 169,
    "name": "Alexander",
    "date": "2025-10-01",
    "rating": 5,
    "text": "Fantastic from start to finish! Super high quality and great service!",
    },
  {
    "id": 170,
    "name": "Miguel",
    "date": "2025-10-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 171,
    "name": "Javis",
    "date": "2025-10-01",
    "rating": 5,
    "text": "She is the absolute best! Made everything a breeze communicating with her is super easy and her cars are always clean! She is such a wonderful host",
    },
  {
    "id": 172,
    "name": "Adrian",
    "date": "2025-09-30",
    "rating": 5,
    "text": "Perfect host, definitivamente vuelvo a rentar con ella, muy atenta y amable",
    },
  {
    "id": 173,
    "name": "Christina",
    "date": "2025-09-30",
    "rating": 5,
    "text": "",
    },
  {
    "id": 174,
    "name": "Omotolani",
    "date": "2025-09-30",
    "rating": 5,
    "text": "",
    },
  {
    "id": 175,
    "name": "Clayton",
    "date": "2025-09-30",
    "rating": 3,
    "text": "It would’ve been nice to have been made aware of the 25$ parking fee once you pick up the car",
    },
  {
    "id": 176,
    "name": "Giovanni",
    "date": "2025-09-30",
    "rating": 5,
    "text": "The best on the best",
    },
  {
    "id": 177,
    "name": "Antonio",
    "date": "2025-09-30",
    "rating": 5,
    "text": "",
    },
  {
    "id": 178,
    "name": "Carlos",
    "date": "2025-09-29",
    "rating": 5,
    "text": "Nice and tidy car",
    },
  {
    "id": 179,
    "name": "Carlos",
    "date": "2025-09-29",
    "rating": 5,
    "text": "Really nice host really attentive 🙏🏻",
    },
  {
    "id": 180,
    "name": "Roxanne",
    "date": "2025-09-28",
    "rating": 5,
    "text": "Great host and wonderful car!",
    },
  {
    "id": 181,
    "name": "Frederick",
    "date": "2025-09-28",
    "rating": 5,
    "text": "",
    },
  {
    "id": 182,
    "name": "Yery",
    "date": "2025-09-28",
    "rating": 5,
    "text": "Auto Exelente !!!!\nLa dueña muy servicial, lo recomiendo 100%",
    },
  {
    "id": 183,
    "name": "Thomas",
    "date": "2025-09-28",
    "rating": 5,
    "text": "",
    },
  {
    "id": 184,
    "name": "Christian",
    "date": "2025-09-28",
    "rating": 5,
    "text": "Loved the car, zero problems",
    },
  {
    "id": 185,
    "name": "Tommy",
    "date": "2025-09-27",
    "rating": 5,
    "text": "",
    },
  {
    "id": 186,
    "name": "Amanda",
    "date": "2025-09-27",
    "rating": 5,
    "text": "Great vehicle and friendly host!",
    },
  {
    "id": 187,
    "name": "Leonardo",
    "date": "2025-09-26",
    "rating": 5,
    "text": "Amazing car!",
    },
  {
    "id": 188,
    "name": "Samantha",
    "date": "2025-09-26",
    "rating": 5,
    "text": "",
    },
  {
    "id": 189,
    "name": "Guillermo",
    "date": "2025-09-26",
    "rating": 5,
    "text": "",
    },
  {
    "id": 190,
    "name": "Raymond",
    "date": "2025-09-26",
    "rating": 5,
    "text": "Truck quality, pickup, location and host were All EXCELLENT!!",
    },
  {
    "id": 191,
    "name": "vegard",
    "date": "2025-09-24",
    "rating": 5,
    "text": "Both the car and the host, Yaineri, were absolutely amazing.\n\nYaineri was incredibly generous and accommodating when we needed to extend our rental, making the whole process stress-free. I can absolutely recommend this to everyone looking for a reliable, fun ride!",
    },
  {
    "id": 192,
    "name": "Matheus",
    "date": "2025-09-24",
    "rating": 5,
    "text": "",
    },
  {
    "id": 193,
    "name": "Glenn",
    "date": "2025-09-23",
    "rating": 5,
    "text": "",
    },
  {
    "id": 194,
    "name": "Jose",
    "date": "2025-09-23",
    "rating": 5,
    "text": "Veryy Amazing Car Host Very Responsive And Helpful when meed Will definitely be renting once Agin In a few Days",
    },
  {
    "id": 195,
    "name": "Edgar",
    "date": "2025-09-22",
    "rating": 5,
    "text": "Great host, always available, and the car was clean",
    },
  {
    "id": 196,
    "name": "Christian",
    "date": "2025-09-22",
    "rating": 5,
    "text": "",
    },
  {
    "id": 197,
    "name": "Eric",
    "date": "2025-09-21",
    "rating": 5,
    "text": "Great vehicle and host was amazing",
    },
  {
    "id": 198,
    "name": "Darrell",
    "date": "2025-09-21",
    "rating": 5,
    "text": "Very helpful and quick response time",
    },
  {
    "id": 199,
    "name": "Juan",
    "date": "2025-09-21",
    "rating": 5,
    "text": "",
    },
  {
    "id": 200,
    "name": "Thomas",
    "date": "2025-09-21",
    "rating": 5,
    "text": "",
    },
  {
    "id": 201,
    "name": "Tennie",
    "date": "2025-09-21",
    "rating": 5,
    "text": "",
    },
  {
    "id": 202,
    "name": "Thiago",
    "date": "2025-09-21",
    "rating": 5,
    "text": "",
    },
  {
    "id": 203,
    "name": "Tomas",
    "date": "2025-09-20",
    "rating": 5,
    "text": "Todo perfecto! El auto y la atención. Siempre disponibles.",
    },
  {
    "id": 204,
    "name": "Theodore",
    "date": "2025-09-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 205,
    "name": "Cruz",
    "date": "2025-09-20",
    "rating": 5,
    "text": "Everything perfect",
    },
  {
    "id": 206,
    "name": "kristin",
    "date": "2025-09-20",
    "rating": 5,
    "text": "Great car, great service! This was My\nsecond time renting it",
    },
  {
    "id": 207,
    "name": "Rosa",
    "date": "2025-09-18",
    "rating": 5,
    "text": "",
    },
  {
    "id": 208,
    "name": "Khadisha",
    "date": "2025-09-18",
    "rating": 5,
    "text": "Outstanding experience. This car is perfect and finding charging stations was very easy",
    },
  {
    "id": 209,
    "name": "Can",
    "date": "2025-09-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 210,
    "name": "Rick",
    "date": "2025-09-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 211,
    "name": "Jefferson",
    "date": "2025-09-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 212,
    "name": "Walter",
    "date": "2025-09-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 213,
    "name": "Daniel",
    "date": "2025-09-17",
    "rating": 5,
    "text": "Great car, great host. Recommended!",
    },
  {
    "id": 214,
    "name": "Pedro",
    "date": "2025-09-16",
    "rating": 4,
    "text": "Very Good Experience The Car was in very good condition. Ahí Enjoy, A Lot, More Than, I Expect The, FSD But. My host was not there. Anytime I need it.",
    },
  {
    "id": 215,
    "name": "Yolanda",
    "date": "2025-09-15",
    "rating": 5,
    "text": "",
    },
  {
    "id": 216,
    "name": "Hurvens",
    "date": "2025-09-15",
    "rating": 5,
    "text": "",
    },
  {
    "id": 217,
    "name": "Dorion",
    "date": "2025-09-15",
    "rating": 5,
    "text": "Great car would book again.",
    },
  {
    "id": 218,
    "name": "Alexander",
    "date": "2025-09-15",
    "rating": 5,
    "text": "",
    },
  {
    "id": 219,
    "name": "Jonathan",
    "date": "2025-09-15",
    "rating": 5,
    "text": "",
    },
  {
    "id": 220,
    "name": "Leon",
    "date": "2025-09-15",
    "rating": 5,
    "text": "Host was amazing . If you’re interested wont be a bad idea at all",
    },
  {
    "id": 221,
    "name": "Deborah",
    "date": "2025-09-15",
    "rating": 5,
    "text": "",
    },
  {
    "id": 222,
    "name": "Emerson",
    "date": "2025-09-14",
    "rating": 5,
    "text": "Execelente anfitrión\nCarro hermoso y limpio\nSuper nice\nRecomendado 100%",
    },
  {
    "id": 223,
    "name": "Seamus",
    "date": "2025-09-14",
    "rating": 5,
    "text": "Super clean. Communicative and helpful.",
    },
  {
    "id": 224,
    "name": "blake",
    "date": "2025-09-13",
    "rating": 5,
    "text": "Absolutely 5 stars!!! Easy to pickup, and return the car. The host was extremely helpful, and made the entire process simple!!",
    },
  {
    "id": 225,
    "name": "liya",
    "date": "2025-09-12",
    "rating": 5,
    "text": "Great communication, best Turo experience we ever had!!!! Best price and nicest people. Thank you so much.",
    },
  {
    "id": 226,
    "name": "Juan Alejandro",
    "date": "2025-09-11",
    "rating": 5,
    "text": "Everything was awesome!",
    },
  {
    "id": 227,
    "name": "Andre",
    "date": "2025-09-11",
    "rating": 5,
    "text": "",
    },
  {
    "id": 228,
    "name": "Jorge",
    "date": "2025-09-11",
    "rating": 5,
    "text": "Tuve una excelente experiencia alquilando con Yaineri 🚗⚡️. Me entregó el Tesla Y 2025 directamente en mi ubicación, todo fue muy rápido y con una comunicación clara y constante. El auto estaba impecable, prácticamente nuevo, hermoso y con mucho espacio. La atención y puntualidad de Yaineri hicieron que el servicio sea de primera. ¡Altamente recomendada y muy agradecido por todo! 🙌✨Muchas gracias !!!.",
    },
  {
    "id": 229,
    "name": "Carlos",
    "date": "2025-09-11",
    "rating": 5,
    "text": "",
    },
  {
    "id": 230,
    "name": "Kenthia",
    "date": "2025-09-10",
    "rating": 5,
    "text": "Amazing host and co-host . Love booking with them.",
    },
  {
    "id": 231,
    "name": "Walter",
    "date": "2025-09-09",
    "rating": 5,
    "text": "",
    },
  {
    "id": 232,
    "name": "Ahmet",
    "date": "2025-09-09",
    "rating": 5,
    "text": "",
    },
  {
    "id": 233,
    "name": "Luis",
    "date": "2025-09-09",
    "rating": 5,
    "text": "Amazing car and host. Tnx",
    },
  {
    "id": 234,
    "name": "Dan",
    "date": "2025-09-08",
    "rating": 5,
    "text": "Top notch host highly recommend. The car is absolutely gorgeous. Thank you.",
    },
  {
    "id": 235,
    "name": "Sierra",
    "date": "2025-09-08",
    "rating": 5,
    "text": "",
    },
  {
    "id": 236,
    "name": "Frederico",
    "date": "2025-09-07",
    "rating": 5,
    "text": "",
    },
  {
    "id": 237,
    "name": "Lavon",
    "date": "2025-09-07",
    "rating": 5,
    "text": "",
    },
  {
    "id": 238,
    "name": "Celso",
    "date": "2025-09-06",
    "rating": 5,
    "text": "It was an incredible experience. The support was incredible too. Everything was great! The car was also amazing. It was my first experience with Turo, and Yainery was an excellent host!",
    },
  {
    "id": 239,
    "name": "Jimmie",
    "date": "2025-09-06",
    "rating": 5,
    "text": "Great car. Super clean. All the features. Easy pickup and drop off. Great host. Best I’ve had yet.",
    },
  {
    "id": 240,
    "name": "Lazariah",
    "date": "2025-09-06",
    "rating": 5,
    "text": "",
    },
  {
    "id": 241,
    "name": "Juan Pablo",
    "date": "2025-09-05",
    "rating": 5,
    "text": "",
    },
  {
    "id": 242,
    "name": "Andre",
    "date": "2025-09-05",
    "rating": 5,
    "text": "",
    },
  {
    "id": 243,
    "name": "Jerry",
    "date": "2025-09-04",
    "rating": 5,
    "text": "Smooth ride. Excellent car. Easy pick up and drop off",
    },
  {
    "id": 244,
    "name": "Miguel",
    "date": "2025-09-04",
    "rating": 5,
    "text": "Great service and communication, the vehicle was just as described.",
    },
  {
    "id": 245,
    "name": "Vanessa",
    "date": "2025-09-04",
    "rating": 5,
    "text": "",
    },
  {
    "id": 246,
    "name": "Tyree",
    "date": "2025-09-04",
    "rating": 5,
    "text": "",
    },
  {
    "id": 247,
    "name": "Alfonso",
    "date": "2025-09-03",
    "rating": 5,
    "text": "",
    },
  {
    "id": 248,
    "name": "Chabrie'",
    "date": "2025-09-03",
    "rating": 5,
    "text": "",
    },
  {
    "id": 249,
    "name": "Justin",
    "date": "2025-09-02",
    "rating": 5,
    "text": "",
    },
  {
    "id": 250,
    "name": "Janecia",
    "date": "2025-09-02",
    "rating": 5,
    "text": "",
    },
  {
    "id": 251,
    "name": "Luis C.",
    "date": "2025-09-02",
    "rating": 5,
    "text": "Amazing ride and host. Love everything about this rental!",
    },
  {
    "id": 252,
    "name": "Alexandra",
    "date": "2025-09-02",
    "rating": 5,
    "text": "",
    },
  {
    "id": 253,
    "name": "Terrell",
    "date": "2025-09-01",
    "rating": 5,
    "text": "Nice clean truck, good communication",
    },
  {
    "id": 254,
    "name": "Shakyra",
    "date": "2025-09-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 255,
    "name": "Diego",
    "date": "2025-09-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 256,
    "name": "Fernando",
    "date": "2025-09-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 257,
    "name": "Anthony",
    "date": "2025-09-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 258,
    "name": "Jason",
    "date": "2025-09-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 259,
    "name": "Eathon",
    "date": "2025-09-01",
    "rating": 5,
    "text": "The car was amazing,the look is stylish just like in the pictures,the pickup and drop off was super easy and easy to navigate",
    },
  {
    "id": 260,
    "name": "Blake",
    "date": "2025-09-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 261,
    "name": "Thiago",
    "date": "2025-08-31",
    "rating": 5,
    "text": "",
    },
  {
    "id": 262,
    "name": "Stanley",
    "date": "2025-08-31",
    "rating": 5,
    "text": "The car was clean and hosts arrived on time to drop off car. They responded really fast about charging questions and coordinating with pick up so the day went super smooth. I’ve had bad experiences where the car wasn’t as described but this car was clean, smelled so good and in excellent condition.",
    },
  {
    "id": 263,
    "name": "Paulo Henrique",
    "date": "2025-08-30",
    "rating": 5,
    "text": "You are amazing and the car superb",
    },
  {
    "id": 264,
    "name": "Victor",
    "date": "2025-08-28",
    "rating": 5,
    "text": "Great car and great service",
    },
  {
    "id": 265,
    "name": "Nicolas",
    "date": "2025-08-28",
    "rating": 5,
    "text": "Great car and great host!! Very helpful at any time!!",
    },
  {
    "id": 266,
    "name": "katiana",
    "date": "2025-08-28",
    "rating": 5,
    "text": "",
    },
  {
    "id": 267,
    "name": "Alejandro",
    "date": "2025-08-28",
    "rating": 5,
    "text": "The car is amazing, it's new and if you like electric cars and trucks you'll love it, we took a trip to Ginnie Spring and it was perfect, the owner explained everything perfectly and the pick up and drop off were fine, only if you pick them up at the airport they will charge you 20 dollars upon departure, everything else is 100 %",
    },
  {
    "id": 268,
    "name": "Roberto",
    "date": "2025-08-28",
    "rating": 5,
    "text": "",
    },
  {
    "id": 269,
    "name": "Alexander",
    "date": "2025-08-28",
    "rating": 5,
    "text": "Very happy with everything!\n\nThe host was very kind to deliver the car to my hotel. All experience was seamless, the car was charged, clean and a pleasure to drive.\n\nAs stated in the description, it also comes with FSD which means that it has a full autopilot. I was impressed with how smooth and good it was. It felt like I rented a car with a chauffeur",
    },
  {
    "id": 270,
    "name": "Konstantin",
    "date": "2025-08-27",
    "rating": 5,
    "text": "",
    },
  {
    "id": 271,
    "name": "Jacklyn",
    "date": "2025-08-27",
    "rating": 5,
    "text": "",
    },
  {
    "id": 272,
    "name": "Carlos",
    "date": "2025-08-27",
    "rating": 5,
    "text": "Great car in great conditions. Very neat and clean. Host was the best! Easy-going and easy to communicate with. Highly recommended!",
    },
  {
    "id": 273,
    "name": "Geizian",
    "date": "2025-08-25",
    "rating": 5,
    "text": "A viagem foi perfeita, o anfitrião foi extremamente receptivo e responde super rápido todas as dúvidas. O carro é incrível!!!",
    },
  {
    "id": 274,
    "name": "Christopher",
    "date": "2025-08-25",
    "rating": 5,
    "text": "Excellent rental experience in Miami. Yainery was a super host, very flexible with arrangements for pick up and collection/drop off. Car (2025 Model Y) was in excellent condition and benefitted from FSD! A must have if you e ever tried it. Transformed the experience and made driving a breeze.\n\nHighly recommend using Yainery, we will look her up when we're back the area.\n\n10 out of 10. 🥰",
    },
  {
    "id": 275,
    "name": "Rey",
    "date": "2025-08-25",
    "rating": 5,
    "text": "",
    },
  {
    "id": 276,
    "name": "rose",
    "date": "2025-08-25",
    "rating": 5,
    "text": "Car was very nice and host was very reliable.",
    },
  {
    "id": 277,
    "name": "Kewyn",
    "date": "2025-08-25",
    "rating": 5,
    "text": "",
    },
  {
    "id": 278,
    "name": "Joseph",
    "date": "2025-08-24",
    "rating": 5,
    "text": "",
    },
  {
    "id": 279,
    "name": "G",
    "date": "2025-08-24",
    "rating": 5,
    "text": "Prefect communication and smooth and clean pick up and drop off , even let me extend the trip for an extra 3 hours !",
    },
  {
    "id": 280,
    "name": "roger",
    "date": "2025-08-24",
    "rating": 5,
    "text": "My trip to Miami wouldnt have been made more comfortable than this rental. The owner is so sweet, kind and patient. She gives you all access to the car via the Tesla app (which comes with full self driving).\nCannot wait for my next visit. Highly recommend the service",
    },
  {
    "id": 281,
    "name": "Will",
    "date": "2025-08-24",
    "rating": 5,
    "text": "Superb communication, vehicle in excellent condition, Appreciated Tesla app access, and FSD was wonderful around Miami",
    },
  {
    "id": 282,
    "name": "Ariel",
    "date": "2025-08-23",
    "rating": 5,
    "text": "Great host overall and a pleasure to rent Teslas from!",
    },
  {
    "id": 283,
    "name": "Tony",
    "date": "2025-08-23",
    "rating": 5,
    "text": "Perfect trip, very good car and attentive host. I recommend it.",
    },
  {
    "id": 284,
    "name": "kristin",
    "date": "2025-08-23",
    "rating": 5,
    "text": "Spacious, nice, and clean! Easy to find at airport and simple drop off as well. Will definitely rent again",
    },
  {
    "id": 285,
    "name": "Amarpratap Singh",
    "date": "2025-08-22",
    "rating": 5,
    "text": "",
    },
  {
    "id": 286,
    "name": "Rafael",
    "date": "2025-08-22",
    "rating": 5,
    "text": "Everything was great WILL be renting again soon.",
    },
  {
    "id": 287,
    "name": "Francisco",
    "date": "2025-08-22",
    "rating": 5,
    "text": "Awesome car and amazing ride today",
    },
  {
    "id": 288,
    "name": "Maude",
    "date": "2025-08-22",
    "rating": 5,
    "text": "",
    },
  {
    "id": 289,
    "name": "Afsheen",
    "date": "2025-08-21",
    "rating": 5,
    "text": "",
    },
  {
    "id": 290,
    "name": "Tamika",
    "date": "2025-08-21",
    "rating": 5,
    "text": "Beautiful experience",
    },
  {
    "id": 291,
    "name": "Luis",
    "date": "2025-08-20",
    "rating": 5,
    "text": "Excellent",
    },
  {
    "id": 292,
    "name": "M",
    "date": "2025-08-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 293,
    "name": "Christian",
    "date": "2025-08-19",
    "rating": 5,
    "text": "",
    },
  {
    "id": 294,
    "name": "Shakyra",
    "date": "2025-08-18",
    "rating": 5,
    "text": "",
    },
  {
    "id": 295,
    "name": "Leavon",
    "date": "2025-08-18",
    "rating": 5,
    "text": "",
    },
  {
    "id": 296,
    "name": "Dariel",
    "date": "2025-08-17",
    "rating": 5,
    "text": "Everything excellent. Great communication, service and car conditions! Hope to rent again with you next time in Miami!",
    },
  {
    "id": 297,
    "name": "Richard",
    "date": "2025-08-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 298,
    "name": "Marshone",
    "date": "2025-08-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 299,
    "name": "Carlos",
    "date": "2025-08-17",
    "rating": 5,
    "text": "Great host fast at communicating and car in excellent condition.",
    },
  {
    "id": 300,
    "name": "Arkeeria",
    "date": "2025-08-17",
    "rating": 5,
    "text": "Smooth ride, host was very sweet !",
    },
  {
    "id": 301,
    "name": "Maria",
    "date": "2025-08-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 302,
    "name": "Charles",
    "date": "2025-08-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 303,
    "name": "Ozge",
    "date": "2025-08-16",
    "rating": 5,
    "text": "Very easy pick up and drop off. Almost new and clean car without any issue. Great thanks to Yainery!",
    },
  {
    "id": 304,
    "name": "George",
    "date": "2025-08-15",
    "rating": 5,
    "text": "",
    },
  {
    "id": 305,
    "name": "Daniel",
    "date": "2025-08-15",
    "rating": 5,
    "text": "Everything about the car, excellent comunication with owner, flexibility at pick up and drop off made everything outstanding. Love the Full self driving, car in top notch quality.",
    },
  {
    "id": 306,
    "name": "Simon",
    "date": "2025-08-15",
    "rating": 5,
    "text": "Excelente servicio y auto, lo volvería a rentar 🤩",
    },
  {
    "id": 307,
    "name": "Steven",
    "date": "2025-08-14",
    "rating": 5,
    "text": "Great host will rent again!",
    },
  {
    "id": 308,
    "name": "George",
    "date": "2025-08-13",
    "rating": 5,
    "text": "The model Y was amazing! I used the full self driving 99% of the time. It is great when you don’t know where you’re going and you just let the car drive itself.",
    },
  {
    "id": 309,
    "name": "Mariano",
    "date": "2025-08-13",
    "rating": 5,
    "text": "The car was so clean ! We love the car ! Tesla model Y is so cool ! The host is so nice ! Thank you so much!",
    },
  {
    "id": 310,
    "name": "pablo",
    "date": "2025-08-13",
    "rating": 5,
    "text": "El carro está perfecto, el servicio fue impecable. Muchas gracias.",
    },
  {
    "id": 311,
    "name": "Emanuel",
    "date": "2025-08-13",
    "rating": 5,
    "text": "The best experience of renting a car. If you are looking to try Self Drive mode, do it, it's the future of driving. Thanks for all !",
    },
  {
    "id": 312,
    "name": "Matthias",
    "date": "2025-08-12",
    "rating": 5,
    "text": "Great",
    },
  {
    "id": 313,
    "name": "Jonathan",
    "date": "2025-08-11",
    "rating": 5,
    "text": "Everything was super smooth and had a great experience overall with the host and the vehicle. Highly recommend!",
    },
  {
    "id": 314,
    "name": "Chiedozie",
    "date": "2025-08-10",
    "rating": 5,
    "text": "Everything was perfect! The pickup and drop-off were easy, and the host was very responsive and understanding. My experience renting this car was seamless.",
    },
  {
    "id": 315,
    "name": "Mike & Jen",
    "date": "2025-08-10",
    "rating": 5,
    "text": "",
    },
  {
    "id": 316,
    "name": "Rachael",
    "date": "2025-08-10",
    "rating": 5,
    "text": "",
    },
  {
    "id": 317,
    "name": "Nimrod",
    "date": "2025-08-10",
    "rating": 5,
    "text": "",
    },
  {
    "id": 318,
    "name": "Nelson",
    "date": "2025-08-10",
    "rating": 5,
    "text": "Muy buen auto maginifico muchas gracias",
    },
  {
    "id": 319,
    "name": "Blaine",
    "date": "2025-08-08",
    "rating": 5,
    "text": "",
    },
  {
    "id": 320,
    "name": "Dominique",
    "date": "2025-08-08",
    "rating": 5,
    "text": "Car was excellent host is always 5 star review will book again.",
    },
  {
    "id": 321,
    "name": "Luca",
    "date": "2025-08-07",
    "rating": 5,
    "text": "",
    },
  {
    "id": 322,
    "name": "Marc",
    "date": "2025-08-06",
    "rating": 5,
    "text": "Great Turo experience! Pickup and drop-off were seamless, and the car was in excellent condition. Full Self-Driving (FSD) worked perfectly in this area—made the trip even more enjoyable. Highly recommend this host and vehicle. Will definitely rent again in the future!",
    },
  {
    "id": 323,
    "name": "Christopher",
    "date": "2025-08-06",
    "rating": 5,
    "text": "",
    },
  {
    "id": 324,
    "name": "Gonzalo",
    "date": "2025-08-04",
    "rating": 5,
    "text": "Great host and great car, thank you!!",
    },
  {
    "id": 325,
    "name": "Sayli",
    "date": "2025-08-04",
    "rating": 5,
    "text": "Amazing",
    },
  {
    "id": 326,
    "name": "Afolabi",
    "date": "2025-08-04",
    "rating": 5,
    "text": "",
    },
  {
    "id": 327,
    "name": "William",
    "date": "2025-08-04",
    "rating": 5,
    "text": "",
    },
  {
    "id": 328,
    "name": "brayan",
    "date": "2025-08-04",
    "rating": 5,
    "text": "",
    },
  {
    "id": 329,
    "name": "Faisal",
    "date": "2025-08-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 330,
    "name": "Andre",
    "date": "2025-08-01",
    "rating": 5,
    "text": "Amazing host and amazing car. Would definitely rent it again.",
    },
  {
    "id": 331,
    "name": "Malachi",
    "date": "2025-07-31",
    "rating": 5,
    "text": "Amazing wonderful and can’t wait to book again",
    },
  {
    "id": 332,
    "name": "Maui",
    "date": "2025-07-31",
    "rating": 5,
    "text": "Perfect ride to discover Miami , autopilot is crazy good !\nYainery was a wonderful host.\nMauruuru (thank you)",
    },
  {
    "id": 333,
    "name": "Hernan Lucas",
    "date": "2025-07-31",
    "rating": 5,
    "text": "",
    },
  {
    "id": 334,
    "name": "Alex",
    "date": "2025-07-30",
    "rating": 5,
    "text": "Host was the best so far, responds instantly, and customer service was the best I have seen",
    },
  {
    "id": 335,
    "name": "Lusanda",
    "date": "2025-07-30",
    "rating": 5,
    "text": "",
    },
  {
    "id": 336,
    "name": "Nicolás R",
    "date": "2025-07-30",
    "rating": 5,
    "text": "What a Car !!!",
    },
  {
    "id": 337,
    "name": "Steffano",
    "date": "2025-07-28",
    "rating": 5,
    "text": "Host was great and very responsive, the car was exactly as portrayed in the picture and description. I would 100% recommend booking with her.",
    },
  {
    "id": 338,
    "name": "Theodore",
    "date": "2025-07-28",
    "rating": 5,
    "text": "we would book again everything was great",
    },
  {
    "id": 339,
    "name": "Kevin",
    "date": "2025-07-28",
    "rating": 5,
    "text": "Friendly host. Easy checkin and checkout. Car was in good and working conditions. No complaints.",
    },
  {
    "id": 340,
    "name": "Geanine",
    "date": "2025-07-28",
    "rating": 5,
    "text": "The Tesla Model Y was like brand new! Super clean and easy to drive. Excellent customer service and communication by Yaineri (the host). Thank you for making it seamless for our trip.",
    },
  {
    "id": 341,
    "name": "Robert",
    "date": "2025-07-28",
    "rating": 5,
    "text": "Fantastic car. Yainey was a great host.",
    },
  {
    "id": 342,
    "name": "Dr. Katy",
    "date": "2025-07-28",
    "rating": 5,
    "text": "Car and host were both lovely. Would rent again.!",
    },
  {
    "id": 343,
    "name": "Anthony",
    "date": "2025-07-28",
    "rating": 5,
    "text": "Great ride and great host!",
    },
  {
    "id": 344,
    "name": "Edgar",
    "date": "2025-07-28",
    "rating": 5,
    "text": "",
    },
  {
    "id": 345,
    "name": "Fernando",
    "date": "2025-07-28",
    "rating": 5,
    "text": "",
    },
  {
    "id": 346,
    "name": "Valmore",
    "date": "2025-07-28",
    "rating": 5,
    "text": "Excellent",
    },
  {
    "id": 347,
    "name": "Ana",
    "date": "2025-07-27",
    "rating": 5,
    "text": "Toda una experiencia",
    },
  {
    "id": 348,
    "name": "Brittany",
    "date": "2025-07-27",
    "rating": 5,
    "text": "Host was great, car was clean and as advertised",
    },
  {
    "id": 349,
    "name": "Gabriel",
    "date": "2025-07-26",
    "rating": 5,
    "text": "Excelente atencion. Super buen host pendiente de todo y responde a cualquier consulta siempre.",
    },
  {
    "id": 350,
    "name": "Nimesh",
    "date": "2025-07-25",
    "rating": 5,
    "text": "Everything was great !",
    },
  {
    "id": 351,
    "name": "Rafael",
    "date": "2025-07-25",
    "rating": 5,
    "text": "",
    },
  {
    "id": 352,
    "name": "Elliot",
    "date": "2025-07-25",
    "rating": 5,
    "text": "",
    },
  {
    "id": 353,
    "name": "MICHEL ANGE",
    "date": "2025-07-23",
    "rating": 5,
    "text": "",
    },
  {
    "id": 354,
    "name": "Gerhard",
    "date": "2025-07-21",
    "rating": 5,
    "text": "",
    },
  {
    "id": 355,
    "name": "Shelby",
    "date": "2025-07-21",
    "rating": 5,
    "text": "Great communication from host, easy pick up, great truck!",
    },
  {
    "id": 356,
    "name": "Eli",
    "date": "2025-07-21",
    "rating": 5,
    "text": "Comfortable vehicle. Host is helpful and quick to respond.",
    },
  {
    "id": 357,
    "name": "Rome",
    "date": "2025-07-20",
    "rating": 5,
    "text": "Yainery’s red Model Y was perfect!",
    },
  {
    "id": 358,
    "name": "stefan",
    "date": "2025-07-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 359,
    "name": "Kirstie",
    "date": "2025-07-20",
    "rating": 5,
    "text": "Great trip!",
    },
  {
    "id": 360,
    "name": "Carolyn",
    "date": "2025-07-20",
    "rating": 5,
    "text": "Everything was easy, car is amazing, 100% would book again!",
    },
  {
    "id": 361,
    "name": "Wilbert",
    "date": "2025-07-19",
    "rating": 5,
    "text": "GREAT! everything perfect was a great communicator and everything was smooth car was very clean and she answered everything in a timely manner",
    },
  {
    "id": 362,
    "name": "Letti",
    "date": "2025-07-19",
    "rating": 5,
    "text": "",
    },
  {
    "id": 363,
    "name": "Darlan",
    "date": "2025-07-19",
    "rating": 5,
    "text": "",
    },
  {
    "id": 364,
    "name": "Nivton",
    "date": "2025-07-17",
    "rating": 5,
    "text": "Fantastic!!",
    },
  {
    "id": 365,
    "name": "James",
    "date": "2025-07-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 366,
    "name": "Christian",
    "date": "2025-07-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 367,
    "name": "Margie",
    "date": "2025-07-15",
    "rating": 5,
    "text": "",
    },
  {
    "id": 368,
    "name": "Joachim",
    "date": "2025-07-14",
    "rating": 5,
    "text": "",
    },
  {
    "id": 369,
    "name": "Khalid",
    "date": "2025-07-14",
    "rating": 5,
    "text": "",
    },
  {
    "id": 370,
    "name": "Kareem",
    "date": "2025-07-14",
    "rating": 5,
    "text": "",
    },
  {
    "id": 371,
    "name": "Zacharry",
    "date": "2025-07-13",
    "rating": 5,
    "text": "",
    },
  {
    "id": 372,
    "name": "Rina",
    "date": "2025-07-12",
    "rating": 5,
    "text": "",
    },
  {
    "id": 373,
    "name": "Deus",
    "date": "2025-07-12",
    "rating": 5,
    "text": "",
    },
  {
    "id": 374,
    "name": "Gian Luca",
    "date": "2025-07-10",
    "rating": 5,
    "text": "Excellent car and service!!",
    },
  {
    "id": 375,
    "name": "Jadah",
    "date": "2025-07-10",
    "rating": 5,
    "text": "",
    },
  {
    "id": 376,
    "name": "Caleb",
    "date": "2025-07-10",
    "rating": 5,
    "text": "",
    },
  {
    "id": 377,
    "name": "Rebecca",
    "date": "2025-07-09",
    "rating": 5,
    "text": "great, clean and nice!",
    },
  {
    "id": 378,
    "name": "Khadijat",
    "date": "2025-07-07",
    "rating": 5,
    "text": "",
    },
  {
    "id": 379,
    "name": "Francisco",
    "date": "2025-07-07",
    "rating": 5,
    "text": "",
    },
  {
    "id": 380,
    "name": "Sidny",
    "date": "2025-07-06",
    "rating": 5,
    "text": "El carro estaba impecablemente limpio , es un carro muy bello y nuevo , the host fue magnífica y la comunicación con ella fue perfecta !",
    },
  {
    "id": 381,
    "name": "Rome",
    "date": "2025-07-06",
    "rating": 5,
    "text": "The Y was perfectly maintained. Thx so much!",
    },
  {
    "id": 382,
    "name": "Henri",
    "date": "2025-07-06",
    "rating": 5,
    "text": "",
    },
  {
    "id": 383,
    "name": "ashley",
    "date": "2025-07-06",
    "rating": 5,
    "text": "",
    },
  {
    "id": 384,
    "name": "harold",
    "date": "2025-07-06",
    "rating": 5,
    "text": "",
    },
  {
    "id": 385,
    "name": "Tonnie",
    "date": "2025-07-05",
    "rating": 5,
    "text": "",
    },
  {
    "id": 386,
    "name": "Renee",
    "date": "2025-07-05",
    "rating": 5,
    "text": "",
    },
  {
    "id": 387,
    "name": "Denzel",
    "date": "2025-07-03",
    "rating": 5,
    "text": "",
    },
  {
    "id": 388,
    "name": "Ricardo Augusto",
    "date": "2025-07-03",
    "rating": 5,
    "text": "Perfect",
    },
  {
    "id": 389,
    "name": "Mingkun",
    "date": "2025-07-03",
    "rating": 5,
    "text": "Everything is great. You definitely need full self driving to drive in Miami lol!! It’s much more convenient and accident free.",
    },
  {
    "id": 390,
    "name": "Ezra",
    "date": "2025-07-03",
    "rating": 5,
    "text": "",
    },
  {
    "id": 391,
    "name": "Bastiaan",
    "date": "2025-07-02",
    "rating": 5,
    "text": "Great car, great host, everything was fantastic. Communication was great and everything went very smooth! Would rent here next time I come to Miami.",
    },
  {
    "id": 392,
    "name": "Lawrence",
    "date": "2025-07-01",
    "rating": 5,
    "text": "",
    },
  {
    "id": 393,
    "name": "Hernan",
    "date": "2025-07-01",
    "rating": 5,
    "text": "Yainery was always available for all our doubts. I’ve highly recommend her.",
    },
  {
    "id": 394,
    "name": "Lucas",
    "date": "2025-07-01",
    "rating": 5,
    "text": "A anfitriã é fantástica! Não tive problemas com ela, super atenciosa, recomendo muito! // The hostess is fantastic! I had no problems with her, super attentive, I highly recommend her!",
    },
  {
    "id": 395,
    "name": "Kenthia",
    "date": "2025-06-30",
    "rating": 5,
    "text": "This host is amazing accommodating respectful everything that you need in a host 10 out of 10. Second time booking and both were amazing.",
    },
  {
    "id": 396,
    "name": "Andres",
    "date": "2025-06-30",
    "rating": 5,
    "text": "Todo excelente muy buena atención.",
    },
  {
    "id": 397,
    "name": "Elliott",
    "date": "2025-06-30",
    "rating": 5,
    "text": "",
    },
  {
    "id": 398,
    "name": "Martin",
    "date": "2025-06-29",
    "rating": 5,
    "text": "All was great. Car amazing. Better than I expected. Host is the best. Answer everything very quick and really helpfull",
    },
  {
    "id": 399,
    "name": "Zuber",
    "date": "2025-06-29",
    "rating": 5,
    "text": "",
    },
  {
    "id": 400,
    "name": "Mellow Pepper",
    "date": "2025-06-29",
    "rating": 5,
    "text": "",
    },
  {
    "id": 401,
    "name": "Reynold",
    "date": "2025-06-28",
    "rating": 5,
    "text": "Such a lovely experience working with Yainery. My first time using Turo and first trip to Miami Beach. She was very helpful with all my questions and patient with my ignorance. She has a beautiful Tesla with full self drive that I am very used to driving personally and it felt right at home driving her car.",
    },
  {
    "id": 402,
    "name": "Elena",
    "date": "2025-06-28",
    "rating": 5,
    "text": "Car was immaculate, smelling fresh and ready to go when I arrived at the airport. Owner was responsive to communication and pleasant to deal with. I will definitely rent from her again when back in town!",
    },
  {
    "id": 403,
    "name": "Mauro",
    "date": "2025-06-28",
    "rating": 5,
    "text": "",
    },
  {
    "id": 404,
    "name": "Aaron",
    "date": "2025-06-26",
    "rating": 5,
    "text": "",
    },
  {
    "id": 405,
    "name": "Mariah",
    "date": "2025-06-26",
    "rating": 5,
    "text": "",
    },
  {
    "id": 406,
    "name": "Carla",
    "date": "2025-06-25",
    "rating": 5,
    "text": "",
    },
  {
    "id": 407,
    "name": "Win",
    "date": "2025-06-25",
    "rating": 5,
    "text": "Everything went well as planned. Full self drive available.",
    },
  {
    "id": 408,
    "name": "Miroslaw",
    "date": "2025-06-25",
    "rating": 5,
    "text": "Yainery is not only a great host, but also a fantastic person. Very nice, punctual and incredibly flexible. My friends and I are very satisfied! The vehicle was super clean and very comfortable. Thank you Yainery! We wish you all the best!",
    },
  {
    "id": 409,
    "name": "Brian",
    "date": "2025-06-25",
    "rating": 5,
    "text": "",
    },
  {
    "id": 410,
    "name": "Dylan",
    "date": "2025-06-24",
    "rating": 5,
    "text": "Great experience! Lovely to deal with! Needed help with something and that went out of there way to help which I really appreciated! Would stronger recommend them.",
    },
  {
    "id": 411,
    "name": "Breno",
    "date": "2025-06-24",
    "rating": 5,
    "text": "Everything was excellent.",
    },
  {
    "id": 412,
    "name": "JC",
    "date": "2025-06-23",
    "rating": 5,
    "text": "Amazing car and host!",
    },
  {
    "id": 413,
    "name": "Siahou",
    "date": "2025-06-23",
    "rating": 5,
    "text": "",
    },
  {
    "id": 414,
    "name": "Lucas",
    "date": "2025-06-23",
    "rating": 5,
    "text": "",
    },
  {
    "id": 415,
    "name": "Paul",
    "date": "2025-06-23",
    "rating": 5,
    "text": "Car was great. Yainery was great. Trip was great. Definitely recommend - 10/10",
    },
  {
    "id": 416,
    "name": "Awek",
    "date": "2025-06-23",
    "rating": 5,
    "text": "",
    },
  {
    "id": 417,
    "name": "Jairo",
    "date": "2025-06-22",
    "rating": 5,
    "text": "Impecable Service. Clean car and increíble Owner.",
    },
  {
    "id": 418,
    "name": "Alan",
    "date": "2025-06-22",
    "rating": 5,
    "text": "",
    },
  {
    "id": 419,
    "name": "Joao",
    "date": "2025-06-22",
    "rating": 5,
    "text": "",
    },
  {
    "id": 420,
    "name": "Nicolas",
    "date": "2025-06-22",
    "rating": 5,
    "text": "",
    },
  {
    "id": 421,
    "name": "LUIS",
    "date": "2025-06-21",
    "rating": 5,
    "text": "",
    },
  {
    "id": 422,
    "name": "Cobi",
    "date": "2025-06-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 423,
    "name": "Shaneah",
    "date": "2025-06-20",
    "rating": 5,
    "text": "Great customer service. I will definitely rent from her again.",
    },
  {
    "id": 424,
    "name": "Paul",
    "date": "2025-06-19",
    "rating": 5,
    "text": "It is noteworthy that this is my second consecutive rental. Notably, I have never rented from the same vehicle. While I am aware that it is a Tesla, I am not referring to that aspect. Instead, I am referring to the excellent customers service.",
    },
  {
    "id": 425,
    "name": "Kwame",
    "date": "2025-06-19",
    "rating": 5,
    "text": "The car was perfect!!! Clean comfortable and the self driving works amazing. If you’re not familiar with the city this helps a lot. Owner was very pleasant and welcoming. Definitely would rent again!",
    },
  {
    "id": 426,
    "name": "GEELISON",
    "date": "2025-06-18",
    "rating": 5,
    "text": "Amazing host, great communication.\nI will definitely book again when I return to Miami! 🌟🌟🌟🌟🌟",
    },
  {
    "id": 427,
    "name": "Thomas",
    "date": "2025-06-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 428,
    "name": "Andy",
    "date": "2025-06-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 429,
    "name": "Brian",
    "date": "2025-06-16",
    "rating": 5,
    "text": "",
    },
  {
    "id": 430,
    "name": "Bryan",
    "date": "2025-06-16",
    "rating": 5,
    "text": "",
    },
  {
    "id": 431,
    "name": "Michael",
    "date": "2025-06-16",
    "rating": 5,
    "text": "Great trip, I may just buy this car for my everyday use, if you got 6+ people on a trip and you in Miami i promise this the car, no hassle & great communication",
    },
  {
    "id": 432,
    "name": "Omotolani",
    "date": "2025-06-16",
    "rating": 5,
    "text": "",
    },
  {
    "id": 433,
    "name": "Leigh",
    "date": "2025-06-15",
    "rating": 5,
    "text": "Great car, fun to drive, very clean.",
    },
  {
    "id": 434,
    "name": "Hernan Lucas",
    "date": "2025-06-15",
    "rating": 5,
    "text": "",
    },
  {
    "id": 435,
    "name": "Jeffrey",
    "date": "2025-06-12",
    "rating": 5,
    "text": "",
    },
  {
    "id": 436,
    "name": "Julian",
    "date": "2025-06-11",
    "rating": 5,
    "text": "This Is The Best Experience That I Have had with the Turo app. She was so amazing and helpful with us and I recommend her 100%. The car is incredible in useful for families with Kids You Feel Like You Are driving a Cruise. If we come back to Miami I will book it again for sure",
    },
  {
    "id": 437,
    "name": "Steven",
    "date": "2025-06-11",
    "rating": 5,
    "text": "Fantastic host, will use again if the car is available when I got back.",
    },
  {
    "id": 438,
    "name": "Martin",
    "date": "2025-06-11",
    "rating": 5,
    "text": "Great car, great host",
    },
  {
    "id": 439,
    "name": "Korbinian",
    "date": "2025-06-11",
    "rating": 5,
    "text": "Everything was great, the car was brand new and there were no problems. The rental company was extremely friendly and reliable.",
    },
  {
    "id": 440,
    "name": "Luis",
    "date": "2025-06-09",
    "rating": 5,
    "text": "Great host the transition was smooth and easy 100% recommended",
    },
  {
    "id": 441,
    "name": "Ugur",
    "date": "2025-06-08",
    "rating": 5,
    "text": "Wonderful host",
    },
  {
    "id": 442,
    "name": "Walter",
    "date": "2025-06-08",
    "rating": 5,
    "text": "Excellent experience driving this car, definitely recommend the car and the turo service, and especially Yainery in particular for his attention and prompt response. We hope to return soon and use this vehicle again.",
    },
  {
    "id": 443,
    "name": "ALFONZA",
    "date": "2025-06-08",
    "rating": 5,
    "text": "Smooth and seamless experience from start to finish. The vehicle was delivered right on time with clear instructions for pickup, making everything simple and stress free. All around great service. Thank you.",
    },
  {
    "id": 444,
    "name": "Jamiere",
    "date": "2025-06-08",
    "rating": 5,
    "text": "",
    },
  {
    "id": 445,
    "name": "Tomas",
    "date": "2025-06-08",
    "rating": 5,
    "text": "",
    },
  {
    "id": 446,
    "name": "Kevin",
    "date": "2025-06-08",
    "rating": 5,
    "text": "",
    },
  {
    "id": 447,
    "name": "Rafael",
    "date": "2025-06-07",
    "rating": 5,
    "text": "Awesome experience, especially the autopilot. Very friendly hosts. Super impressed! Highly recommend 🚀",
    },
  {
    "id": 448,
    "name": "Jonathan",
    "date": "2025-06-04",
    "rating": 5,
    "text": "Host was super nice and helpful, and car was amazing would recommend this host made drop off and pick up super easy",
    },
  {
    "id": 449,
    "name": "Lucy",
    "date": "2025-06-04",
    "rating": 5,
    "text": "2nd time renting and a 5 star ⭐️ experience in every way again. Very understanding and accommodating host! Cant say enough good things! Also these cars with autopilot are amazing!",
    },
  {
    "id": 450,
    "name": "Максим",
    "date": "2025-06-04",
    "rating": 5,
    "text": "The perfect host with the perfect car",
    },
  {
    "id": 451,
    "name": "Cesar",
    "date": "2025-06-03",
    "rating": 5,
    "text": "Yainery was an excellent host, the car was amazing!!! Driving with FSD was like living in the future. Definitely will drive again.",
    },
  {
    "id": 452,
    "name": "Cristian",
    "date": "2025-06-03",
    "rating": 5,
    "text": "everything was awesome, we booked with really short notice, and had no issues, I’d book again",
    },
  {
    "id": 453,
    "name": "Juan",
    "date": "2025-06-02",
    "rating": 5,
    "text": "As usual. Perfect at in perfect conditions",
    },
  {
    "id": 454,
    "name": "Sandro",
    "date": "2025-06-02",
    "rating": 5,
    "text": "",
    },
  {
    "id": 455,
    "name": "Arash",
    "date": "2025-06-02",
    "rating": 5,
    "text": "Amazing car and host!",
    },
  {
    "id": 456,
    "name": "CYRIL",
    "date": "2025-06-01",
    "rating": 5,
    "text": "Fantastic host as usual ! Thank you !",
    },
  {
    "id": 457,
    "name": "Monica",
    "date": "2025-06-01",
    "rating": 5,
    "text": "The car was nice and accommodating the whole group, the host was quick to answer any questions.",
    },
  {
    "id": 458,
    "name": "Darya",
    "date": "2025-05-31",
    "rating": 5,
    "text": "",
    },
  {
    "id": 459,
    "name": "Paul",
    "date": "2025-05-31",
    "rating": 5,
    "text": "Lovely car beautiful 🤩 I LOVE 💕 IT",
    },
  {
    "id": 460,
    "name": "Vladimyr",
    "date": "2025-05-30",
    "rating": 5,
    "text": "",
    },
  {
    "id": 461,
    "name": "Louise",
    "date": "2025-05-30",
    "rating": 5,
    "text": "So responsive and helpful!",
    },
  {
    "id": 462,
    "name": "M",
    "date": "2025-05-30",
    "rating": 5,
    "text": "Great host, always available and extremely helpful!! Car is amazing!!",
    },
  {
    "id": 463,
    "name": "Jasmine",
    "date": "2025-05-29",
    "rating": 5,
    "text": "",
    },
  {
    "id": 464,
    "name": "Kareem",
    "date": "2025-05-26",
    "rating": 5,
    "text": "",
    },
  {
    "id": 465,
    "name": "Ilan",
    "date": "2025-05-26",
    "rating": 5,
    "text": "Host is highly communicative and reliable. Car was in mind condition.",
    },
  {
    "id": 466,
    "name": "Luis",
    "date": "2025-05-26",
    "rating": 5,
    "text": "Amazing car from a fantastic host!",
    },
  {
    "id": 467,
    "name": "Malesa",
    "date": "2025-05-26",
    "rating": 5,
    "text": "Car was very spacious and really big.",
    },
  {
    "id": 468,
    "name": "Richard",
    "date": "2025-05-25",
    "rating": 5,
    "text": "Quick responses and great host. Great car as well!",
    },
  {
    "id": 469,
    "name": "Taylor",
    "date": "2025-05-25",
    "rating": 5,
    "text": "",
    },
  {
    "id": 470,
    "name": "YIZHE",
    "date": "2025-05-24",
    "rating": 5,
    "text": "",
    },
  {
    "id": 471,
    "name": "Kamal",
    "date": "2025-05-24",
    "rating": 5,
    "text": "Amazing Host !\nEverything was easy and smooth.",
    },
  {
    "id": 472,
    "name": "Veronika",
    "date": "2025-05-24",
    "rating": 5,
    "text": "I recently had the pleasure of renting a Tesla Y from Yai, and I can’t say enough about how wonderful the entire experience was. The car itself was absolutely stunning—luxurious, impeccably clean, and exactly as described. It was a real treat to drive and brought a bit of brightness to a stressful time while my own car was being repaired and eventually totaled. Yai was an exceptional host: warm, accommodating, and always quick to reply to any questions or concerns. She made the whole process feel easy and comforting, even as the rental kept extending unexpectedly. Her attention to detail and personal kindness set her apart from anyone I’ve rented from before. I am deeply grateful for her understanding and flexibility. If you’re looking for a truly top-notch rental experience with someone who goes the extra mile, Yai is the perfect choice!",
    },
  {
    "id": 473,
    "name": "Vladimyr",
    "date": "2025-05-24",
    "rating": 5,
    "text": "Great car",
    },
  {
    "id": 474,
    "name": "Umut",
    "date": "2025-05-24",
    "rating": 5,
    "text": "Great experience with that car and great host. Thank you",
    },
  {
    "id": 475,
    "name": "Lucy",
    "date": "2025-05-23",
    "rating": 5,
    "text": "Amazing host. Excellent car. The self driving is an absolute game changer!",
    },
  {
    "id": 476,
    "name": "Максим",
    "date": "2025-05-21",
    "rating": 5,
    "text": "Great car in perfect condition! Great host always on call answers any even stupid questions! Already rented for my next trip",
    },
  {
    "id": 477,
    "name": "Arash",
    "date": "2025-05-20",
    "rating": 5,
    "text": "Great car and host",
    },
  {
    "id": 478,
    "name": "Rodenise",
    "date": "2025-05-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 479,
    "name": "Thijs",
    "date": "2025-05-20",
    "rating": 5,
    "text": "Yainery was an absolute fenomenal host and the car was great. I asked if I could return the car to a different location than pickup and if pickup could be arranged a little earlier and non of that was any problem. Also, the car is equipped with Full Self Driving, which was very nice to use.",
    },
  {
    "id": 480,
    "name": "Jacob",
    "date": "2025-05-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 481,
    "name": "Edner",
    "date": "2025-05-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 482,
    "name": "Stacy",
    "date": "2025-05-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 483,
    "name": "Thomas",
    "date": "2025-05-19",
    "rating": 5,
    "text": "Car was clean and in great condition. Host was very attentive and kind. Highly recommend her!",
    },
  {
    "id": 484,
    "name": "Gerardo",
    "date": "2025-05-19",
    "rating": 5,
    "text": "The service and the car were excelent!",
    },
  {
    "id": 485,
    "name": "Rodrigo",
    "date": "2025-05-19",
    "rating": 5,
    "text": "",
    },
  {
    "id": 486,
    "name": "Jason",
    "date": "2025-05-18",
    "rating": 4,
    "text": "Great vehicle love the FSD feature",
    },
  {
    "id": 487,
    "name": "2stroke",
    "date": "2025-05-18",
    "rating": 5,
    "text": "",
    },
  {
    "id": 488,
    "name": "Jermaine",
    "date": "2025-05-18",
    "rating": 5,
    "text": "Loved the car thanks",
    },
  {
    "id": 489,
    "name": "Blake",
    "date": "2025-05-17",
    "rating": 5,
    "text": "Great host. Responded quickly and hospitable.",
    },
  {
    "id": 490,
    "name": "Janiece",
    "date": "2025-05-17",
    "rating": 5,
    "text": "This Tesla Model 3 was phenomenal and one of the smoothest cars I’ve ever drove. The host response time was very fast and the pick up & drop off was a breeze. I will definitely book again!",
    },
  {
    "id": 491,
    "name": "Alan",
    "date": "2025-05-14",
    "rating": 5,
    "text": "Everything was great.",
    },
  {
    "id": 492,
    "name": "Gerardo",
    "date": "2025-05-14",
    "rating": 5,
    "text": "",
    },
  {
    "id": 493,
    "name": "Kevin",
    "date": "2025-05-12",
    "rating": 5,
    "text": "Amazing host and super clean vehicle. Above and beyond to answer my questions as a first time user",
    },
  {
    "id": 494,
    "name": "Jess",
    "date": "2025-05-12",
    "rating": 5,
    "text": "Quality was excellent and great communication!",
    },
  {
    "id": 495,
    "name": "Jan",
    "date": "2025-05-12",
    "rating": 5,
    "text": "I can’t say enough about this amazing host. Such a professional and organized process. Super responsive and very accommodating. The car was clean and equipped with everything needed to get going. 10/10 great experience.",
    },
  {
    "id": 496,
    "name": "Arash",
    "date": "2025-05-12",
    "rating": 5,
    "text": "",
    },
  {
    "id": 497,
    "name": "Maurice",
    "date": "2025-05-10",
    "rating": 5,
    "text": "",
    },
  {
    "id": 498,
    "name": "Michael",
    "date": "2025-05-08",
    "rating": 5,
    "text": "Car was great, communication was professional and prompt. Definitely recommend",
    },
  {
    "id": 499,
    "name": "Makyla",
    "date": "2025-05-08",
    "rating": 5,
    "text": "",
    },
  {
    "id": 500,
    "name": "Shakari",
    "date": "2025-05-08",
    "rating": 5,
    "text": "",
    },
  {
    "id": 501,
    "name": "Frederico",
    "date": "2025-05-06",
    "rating": 5,
    "text": "Perfect",
    },
  {
    "id": 502,
    "name": "Henry",
    "date": "2025-05-06",
    "rating": 5,
    "text": "",
    },
  {
    "id": 503,
    "name": "Lorenzo",
    "date": "2025-05-05",
    "rating": 5,
    "text": "",
    },
  {
    "id": 504,
    "name": "Michael",
    "date": "2025-05-05",
    "rating": 5,
    "text": "",
    },
  {
    "id": 505,
    "name": "Jhon",
    "date": "2025-05-04",
    "rating": 5,
    "text": "",
    },
  {
    "id": 506,
    "name": "Angel",
    "date": "2025-05-04",
    "rating": 5,
    "text": "",
    },
  {
    "id": 507,
    "name": "Moises",
    "date": "2025-05-04",
    "rating": 5,
    "text": "",
    },
  {
    "id": 508,
    "name": "Ivan",
    "date": "2025-05-02",
    "rating": 5,
    "text": "",
    },
  {
    "id": 509,
    "name": "Daniel",
    "date": "2025-05-01",
    "rating": 5,
    "text": "Car in excellent condition. Host great communication.",
    },
  {
    "id": 510,
    "name": "Hernan",
    "date": "2025-04-30",
    "rating": 5,
    "text": "This car is amazing!!!!!",
    },
  {
    "id": 511,
    "name": "Jason",
    "date": "2025-04-29",
    "rating": 5,
    "text": "Very clean, handled nicely and all features advertised are working perfectly. Honestly very happy at the seamlessness process from day one with both the car and my hosts, highly recommended these folks",
    },
  {
    "id": 512,
    "name": "Eissa",
    "date": "2025-04-29",
    "rating": 5,
    "text": "",
    },
  {
    "id": 513,
    "name": "Kevin",
    "date": "2025-04-29",
    "rating": 5,
    "text": "A five-star service from Yainery! She provided invaluable assistance before, during, and after the rental. I will definitely rent again without hesitation.",
    },
  {
    "id": 514,
    "name": "Luis",
    "date": "2025-04-28",
    "rating": 5,
    "text": "Car was in excellent conditions, really enjoyed driving it. Would definitely rent it again!",
    },
  {
    "id": 515,
    "name": "Juan",
    "date": "2025-04-27",
    "rating": 5,
    "text": "Perfect! As usual",
    },
  {
    "id": 516,
    "name": "Isaac",
    "date": "2025-04-27",
    "rating": 5,
    "text": "Great host",
    },
  {
    "id": 517,
    "name": "Jordyn",
    "date": "2025-04-25",
    "rating": 5,
    "text": "Great, answered all my questions. Super helpful.",
    },
  {
    "id": 518,
    "name": "Kenthia",
    "date": "2025-04-25",
    "rating": 5,
    "text": "Very helpful and smooth transaction.",
    },
  {
    "id": 519,
    "name": "Xeuris",
    "date": "2025-04-24",
    "rating": 5,
    "text": "Excellent service!!!",
    },
  {
    "id": 520,
    "name": "Henry",
    "date": "2025-04-24",
    "rating": 3,
    "text": "Great car and easy experience, car just needs new brakes",
    },
  {
    "id": 521,
    "name": "derek",
    "date": "2025-04-23",
    "rating": 5,
    "text": "",
    },
  {
    "id": 522,
    "name": "Elias",
    "date": "2025-04-22",
    "rating": 5,
    "text": "Great trip.",
    },
  {
    "id": 523,
    "name": "Richard",
    "date": "2025-04-21",
    "rating": 5,
    "text": "",
    },
  {
    "id": 524,
    "name": "Miguel",
    "date": "2025-04-20",
    "rating": 5,
    "text": "Everything was excellent!",
    },
  {
    "id": 525,
    "name": "D'Avion",
    "date": "2025-04-20",
    "rating": 5,
    "text": "",
    },
  {
    "id": 526,
    "name": "Samantha",
    "date": "2025-04-19",
    "rating": 5,
    "text": "Car was great and parked in a convenient location at the airport for us.",
    },
  {
    "id": 527,
    "name": "Darya",
    "date": "2025-04-19",
    "rating": 5,
    "text": "",
    },
  {
    "id": 528,
    "name": "Javis",
    "date": "2025-04-19",
    "rating": 5,
    "text": "",
    },
  {
    "id": 529,
    "name": "Javis",
    "date": "2025-04-19",
    "rating": 5,
    "text": "",
    },
  {
    "id": 530,
    "name": "Licio",
    "date": "2025-04-18",
    "rating": 5,
    "text": "",
    },
  {
    "id": 531,
    "name": "Andrey",
    "date": "2025-04-18",
    "rating": 5,
    "text": "Really grateful for the experience! Car is amazing, Yainery is great, always ready to help and really client oriented! Thank you once again!",
    },
  {
    "id": 532,
    "name": "keerthikanth",
    "date": "2025-04-18",
    "rating": 5,
    "text": "She is the best!!! One of those rare host who is always willing to accommodate!!",
    },
  {
    "id": 533,
    "name": "Vivian",
    "date": "2025-04-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 534,
    "name": "Fernando",
    "date": "2025-04-17",
    "rating": 5,
    "text": "",
    },
  {
    "id": 535,
    "name": "Jacob",
    "date": "2025-04-17",
    "rating": 5,
    "text": "The entire experience was a breeze",
    },
  {
    "id": 536,
    "name": "Duval",
    "date": "2025-04-16",
    "rating": 5,
    "text": "Fantastic car, host was very accommodating! Easy rental, will book again!",
    },
  {
    "id": 537,
    "name": "Jon",
    "date": "2025-04-16",
    "rating": 5,
    "text": "I normally don’t give reviews but this was exceptional! The host was so responsive the entire time and even installed a car seat for my son. Car was super clean and smelled great. The host was responsive and accommodating for anything I needed. Great experience",
    },
  {
    "id": 538,
    "name": "Florian",
    "date": "2025-04-15",
    "rating": 5,
    "text": "",
    },
  {
    "id": 539,
    "name": "Lizbeth",
    "date": "2025-04-15",
    "rating": 5,
    "text": "Incredible service, incredible attention and car was amazing! Definitely renting again. 100% great experience. 👍🏼😁",
    },
  {
    "id": 540,
    "name": "Duval",
    "date": "2025-04-14",
    "rating": 5,
    "text": "It was great Car. The host was perfect. Very communicative. Will rent again",
    },
  {
    "id": 541,
    "name": "Meeka",
    "date": "2025-04-14",
    "rating": 5,
    "text": "I was so pleased with the vehicle. The host was amazing and flexible. I will be renting again.",
    },
  {
    "id": 542,
    "name": "Crystal",
    "date": "2025-04-14",
    "rating": 5,
    "text": "Great car. Yainery was very responsive and helpful. Would definitely recommend.",
    },
  {
    "id": 543,
    "name": "Thomas",
    "date": "2025-04-13",
    "rating": 5,
    "text": "Great host. Friendly and very helpful.\nBest possible experience.",
    },
  {
    "id": 544,
    "name": "Alex",
    "date": "2025-04-12",
    "rating": 5,
    "text": "",
    },
  {
    "id": 545,
    "name": "Paul",
    "date": "2025-04-12",
    "rating": 5,
    "text": "",
    },
  {
    "id": 546,
    "name": "Ashish",
    "date": "2025-04-12",
    "rating": 5,
    "text": "I recently had the pleasure of renting a vehicle from this host, and I must say it was an overwhelmingly positive experience. From start to finish, the host was absolutely awesome – incredibly accommodating, responsive, and a genuine pleasure to communicate with.\n\nFurthermore, the physical condition of the car was impeccable. It was clean, well-maintained, and a joy to drive. It's clear that the host takes great pride in ensuring their vehicle is in top-notch shape for renters.\n\nAll in all, this was a truly great experience, and I will absolutely be booking with this host again without any second thoughts.\n\nMinor Feedback:\n\nThe only minor inconvenience I encountered during my rental was with the software aspect of the car. My Tesla driver profile unfortunately wouldn't activate. While this didn't significantly impact my overall enjoyment, I suspect it might be due to the car's software not being up to the latest version.\n\nThis is just a small piece of feedback for the host to consider – ensuring the Tesla software is up-to-date would undoubtedly provide an even smoother experience for future users.\n\nConclusion:\n\nDespite this very minor software glitch, everything else about this rental was flawless. The exceptional host and the excellent condition of the car far outweighed this small issue. I highly recommend this host and will definitely be a repeat customer!",
    },
  {
    "id": 547,
    "name": "Carlos",
    "date": "2025-04-12",
    "rating": 5,
    "text": "Awesome host",
    },
  {
    "id": 548,
    "name": "Christopher",
    "date": "2026-02-19",
    "rating": 5,
    "text": "The Tesla was in amazing condition and so much fun to drive. Communication with Yainery was super easy and had no issues collecting and returning the car. Would not hesitate renting from them again. ",
    "photo": "/reviews/Christopher2026-02-19.jpg"
  },
  {
    "id": 549,
    "name": "Joy",
    "date": "2026-02-16",
    "rating": 5,
    "text": "Fantastic car and host.  Will rent again.  Thanks!!",
    "photo": "/reviews/Joy2026-02-16.jpg"
  },
  {
    "id": 550,
    "name": "Martin",
    "date": "2026-02-15",
    "rating": 5,
    "text": "Yainery is the best host. Anyone should rent with her",
    },
  {
    "id": 551,
    "name": "Margaret",
    "date": "2026-02-15",
    "rating": 5,
    "text": "The car was great",
    },
  {
    "id": 552,
    "name": "Dexter",
    "date": "2026-02-15",
    "rating": 5,
    "text": "Thank you !",
    "photo": "/reviews/Dexter2026-02-15.jpg"
  },
  {
    "id": 553,
    "name": "CYRIL",
    "date": "2026-02-12",
    "rating": 5,
    "text": "Perfect as always",
    "photo": "/reviews/CYRIL2026-02-12.jpg"
  },
  {
    "id": 554,
    "name": "Miguel",
    "date": "2026-02-12",
    "rating": 5,
    "text": "It is always a perfect experience with this amazing Team. The car in perfect condition and the communication couldn't be better. I will keep using their services, my favorite in Miami!",
    },
  {
    "id": 555,
    "name": "Smiller",
    "date": "2026-02-11",
    "rating": 5,
    "text": "Amazing hosts!!! Congratulations!!!",
    },
  {
    "id": 556,
    "name": "Henrique Leopoldo D.",
    "date": "2026-02-11",
    "rating": 5,
    "text": "The service was perfect. Friendly and clear communication, unlike others. Super fluid. The car was perfect. Thank you",
    },
  {
    "id": 557,
    "name": "Muhammad Ahad",
    "date": "2026-02-08",
    "rating": 5,
    "text": "Absolutely amazing, great host any questions I had got answered promptly, car was great nice and clean no issues at all, thank you for making this stress free.",
    },
  {
    "id": 558,
    "name": "Stanley",
    "date": "2026-02-08",
    "rating": 5,
    "text": "Fantastic experience! Easy pickup, great communication, and an excellent car. Couldn't have asked for a better trip, would definitely book again.",
    },
  {
    "id": 559,
    "name": "Moises",
    "date": "2026-02-07",
    "rating": 5,
    "text": "Awesome, great at all. Car ",
    },
  {
    "id": 560,
    "name": "Oğuz Can",
    "date": "2026-02-05",
    "rating": 5,
    "text": "It was amazing service they are so helpfull and friendly. Also the car is amazing ! Thank you !",
    },
  {
    "id": 561,
    "name": "Brandon",
    "date": "2026-02-01",
    "rating": 5,
    "text": "Really great host and very flexible! Will use again",
    "photo": "/reviews/Brandon2026-02-01.jpg"
  },
  {
    "id": 562,
    "name": "Ernesto",
    "date": "2026-01-30",
    "rating": 5,
    "text": "Everything great, very communicative",
    "photo": "/reviews/Ernesto2026-01-30.jpg"
  },
  {
    "id": 563,
    "name": "Lisa",
    "date": "2026-01-30",
    "rating": 5,
    "text": "Hostess was amazing!!! Very responsive!!",
    },
  {
    "id": 564,
    "name": "Roman",
    "date": "2026-01-30",
    "rating": 5,
    "text": "Top-notch car and an attentive host! Also, don't forget to add FSD to your booking. It's a game changer.",
    },
  {
    "id": 565,
    "name": "Minyeong",
    "date": "2026-01-28",
    "rating": 5,
    "text": "I was planning a 1-night, 2-day trip from Miami to Key West and was specifically looking for a Tesla with FSD. Thanks to this rental, the trip turned out absolutely amazing.\n\nThe host was very responsive and helpful, and the car was in excellent condition — clean, well-maintained, and drove perfectly the entire trip. The long drive was incredibly comfortable, which made the whole experience even better.\n\nI couldn't have asked for a better rental experience and would 100% recommend this car to anyone looking to rent a Tesla!\n",
    },
  {
    "id": 566,
    "name": "Teleaya",
    "date": "2026-01-27",
    "rating": 5,
    "text": "Thank you ",
    },
  {
    "id": 567,
    "name": "Maurice",
    "date": "2026-01-25",
    "rating": 5,
    "text": "Great 👍🏻 ",
    },
  {
    "id": 568,
    "name": "Sanjit",
    "date": "2026-01-25",
    "rating": 5,
    "text": "Fantastic experience - have rented multiple times",
    },
  {
    "id": 569,
    "name": "weilie",
    "date": "2026-01-24",
    "rating": 5,
    "text": "The check in and check out are very smooth.  The car is superb!",
    "photo": "/reviews/weilie2026-01-24.jpg"
  },
  {
    "id": 570,
    "name": "Cobi",
    "date": "2026-01-20",
    "rating": 5,
    "text": "Thanks again \n",
    "photo": "/reviews/Cobi2026-01-20.jpg"
  },
  {
    "id": 571,
    "name": "ERIC",
    "date": "2026-01-20",
    "rating": 5,
    "text": "Nice car and good owner communication. Definitely recommended. ",
    "photo": "/reviews/ERIC2026-01-20.jpg"
  },
  {
    "id": 572,
    "name": "Rick",
    "date": "2026-01-19",
    "rating": 5,
    "text": "Excellent owner communication. Car was fantastic! Very clean, fully functioned. FSD is very impressive! Would 100% rent again. ",
    "photo": "/reviews/Rick2026-01-19.jpg"
  },
  {
    "id": 573,
    "name": "Michelle",
    "date": "2026-01-16",
    "rating": 5,
    "text": "This was my best experience.. I come to Miami 3 times a year and I always rent a Tesla. Communication was very good. Car was very clean..Gave smooth ride. Directions were very clear on how & Where to find the car. Will definitely use you again. Thank you!",
    "photo": "/reviews/Michelle2026-01-16.jpg"
  },
  {
    "id": 574,
    "name": "Nicholas",
    "date": "2026-01-16",
    "rating": 5,
    "text": "Car was super clean. Host is responsive, friendly and accommodating. Would definitely recommend. ",
    "photo": "/reviews/Nicholas2026-01-16.jpg"
  },
  {
    "id": 575,
    "name": "Eduardo",
    "date": "2026-01-15",
    "rating": 5,
    "text": "Amazing car, thank you!\n",
    "photo": "/reviews/Eduardo2026-01-15.jpg"
  },
  {
    "id": 576,
    "name": "Robert",
    "date": "2026-01-15",
    "rating": 5,
    "text": "Pickup was a breeze, and the car was fantastic! FSD road trip is the only way to go ",
    "photo": "/reviews/Robert2026-01-15.jpg"
  },
  {
    "id": 577,
    "name": "Björn",
    "date": "2026-01-09",
    "rating": 5,
    "text": "Amazing experience! The car was great and FSD 14 was awesome, made the trip easy and relaxed. Super friendly host, always quick to help and insanely fast to respond.",
    },
  {
    "id": 578,
    "name": "Christian Gustavo",
    "date": "2026-01-09",
    "rating": 5,
    "text": "I'm truly very disappointed!!!\nthat I can't give 10 stars to the service provided by your host, Yaineri. She was attentive from the very first minute, paying attention to every detail and answering every question I had. The Tesla is a car I would definitely rent again; it's an incredible experience. I'm never renting a car through traditional agencies again! The delivery and return process is completely streamlined.",
    },
  {
    "id": 579,
    "name": "Richard",
    "date": "2026-01-08",
    "rating": 5,
    "text": "Amazing car ! If you rent a TESLA without FSD you're missing out ! Hosts are beyond GREAT! Super responsive . Super accommodating! Will definitely be a repeat renter ",
    },
  {
    "id": 580,
    "name": "Julian",
    "date": "2026-01-06",
    "rating": 5,
    "text": "Great !",
    "photo": "/reviews/Julian2026-01-06.jpg"
  },
  {
    "id": 581,
    "name": "Dan",
    "date": "2026-01-05",
    "rating": 5,
    "text": "FSD was the best!!! ",
    "photo": "/reviews/Dan2026-01-05.jpg"
  },
  {
    "id": 582,
    "name": "Rosa",
    "date": "2026-01-04",
    "rating": 5,
    "text": "Excellent service, the car impeccable and economical. Very attentive and friendly hostess. Thank you very much!",
    },
  {
    "id": 583,
    "name": "Kenneth",
    "date": "2026-01-04",
    "rating": 5,
    "text": "This is an awesome car! It was delivered, clean as can be, to our arrival point. It has every feature Tesla offers and all of the accessories needed for a great trip. Thanks!",
    "photo": "/reviews/Kenneth2026-01-04.jpg"
  },
  {
    "id": 584,
    "name": "Bryan",
    "date": "2026-01-03",
    "rating": 5,
    "text": "Excellent host and perfect vehicle! Easy to work with. Definitely recommend this host and car. ",
    "photo": "/reviews/Bryan2026-01-03.jpg"
  },
  {
    "id": 585,
    "name": "Daniel",
    "date": "2026-01-02",
    "rating": 5,
    "text": "Excellent car and amazing hosts!! ",
    "photo": "/reviews/Daniel2026-01-02.jpg"
  }
];
